package org.open2jam.gui;

import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import org.open2jam.gui.parts.MusicSelection;
import org.open2jam.gui.parts.Configuration;


/**
 *
 * @author CdK
 */
public class Interface extends javax.swing.JFrame implements WindowListener
{
    
    private MusicSelection musicSelection;
    private Configuration configuration;

    /** Creates new form Interface */
    public Interface() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        musicSelection = new MusicSelection();
        configuration = new Configuration();
        
        Tabs.addTab("Music Selection", musicSelection);
        Tabs.addTab("Configuration", configuration);
        
        this.addWindowListener(this);
    }
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tabs = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Open2Jam");
        setMinimumSize(new java.awt.Dimension(950, 800));

        Tabs.setMinimumSize(new java.awt.Dimension(930, 730));
        Tabs.setPreferredSize(new java.awt.Dimension(950, 800));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tabs, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tabs, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        Tabs.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Tabs;
    // End of variables declaration//GEN-END:variables

    @Override
    public void windowOpened(WindowEvent we) {
        
    }

    @Override
    public void windowClosing(WindowEvent we) {
        musicSelection.windowClosing();
    }

    @Override
    public void windowClosed(WindowEvent we) {
        
    }

    @Override
    public void windowIconified(WindowEvent we) {
        
    }

    @Override
    public void windowDeiconified(WindowEvent we) {
        
    }

    @Override
    public void windowActivated(WindowEvent we) {
        
    }

    @Override
    public void windowDeactivated(WindowEvent we) {
        
    }
}
