/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * KeyEventListener.java
 *
 * Created on 20-feb-2011, 22:10:54
 */

package org.open2jam.gui;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

/**
 *
 * @author CdK
 */
public class KeyEventListener extends javax.swing.JFrame implements KeyListener {

    private int row = -1;
    private KeyEvent ke;

    /** Creates new form KeyEventListener */
    public KeyEventListener(int row) {
        this.row = row;

        initComponents();
        initLogic();
        this.setLocationRelativeTo(null);
    }

    private void initLogic()
    {
        this.setTitle("Assign for "+Configuration.getTableValue(this.row, 0));
        lbl_assign.setText(Configuration.getTableValue(this.row, 0));
        lbl_lastassign.setText(Configuration.getTableValue(this.row, 1));

        if(this.row<0) this.setVisible(false);
        else           txt_newassign.setText("Press a key");

        txt_newassign.addKeyListener(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_newassign = new javax.swing.JTextField();
        lbl_assing1 = new javax.swing.JLabel();
        lbl_lastassign1 = new javax.swing.JLabel();
        lbl_newassign1 = new javax.swing.JLabel();
        lbl_assign = new javax.swing.JLabel();
        lbl_lastassign = new javax.swing.JLabel();
        btn_ok = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();

        setTitle("Assign key to NOTE");

        txt_newassign.setEditable(false);

        lbl_assing1.setText("Assign to:");

        lbl_lastassign1.setText("Last assign:");

        lbl_newassign1.setText("New assign:");

        lbl_assign.setText("jLabel4");

        lbl_lastassign.setText("jLabel5");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_lastassign1)
                    .addComponent(lbl_assing1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_assign)
                    .addComponent(lbl_lastassign))
                .addContainerGap(227, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbl_newassign1)
                    .addGap(18, 18, 18)
                    .addComponent(txt_newassign, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(79, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_assing1)
                    .addComponent(lbl_assign))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_lastassign1)
                    .addComponent(lbl_lastassign))
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(60, 60, 60)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_newassign1)
                        .addComponent(txt_newassign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(20, Short.MAX_VALUE)))
        );

        btn_ok.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_ok.setText("OK");
        btn_ok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_okMouseClicked(evt);
            }
        });

        btn_cancel.setText("cancel");
        btn_cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cancelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_ok)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_cancel))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancel)
                    .addComponent(btn_ok))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_btn_cancelMouseClicked

    private void btn_okMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_okMouseClicked
        if(ke != null)
            Configuration.setTableValue(ke, row, 1);

        this.setVisible(false);
    }//GEN-LAST:event_btn_okMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton btn_cancel;
    private static javax.swing.JButton btn_ok;
    private static javax.swing.JPanel jPanel1;
    private static javax.swing.JLabel lbl_assign;
    private static javax.swing.JLabel lbl_assing1;
    private static javax.swing.JLabel lbl_lastassign;
    private static javax.swing.JLabel lbl_lastassign1;
    private static javax.swing.JLabel lbl_newassign1;
    private static javax.swing.JTextField txt_newassign;
    // End of variables declaration//GEN-END:variables

    public void keyTyped(KeyEvent e) {
        //NOTHING
    }

    public void keyPressed(KeyEvent e) {
        this.ke = e;
        txt_newassign.setText(translateKeyEvent(e));
    }

    public void keyReleased(KeyEvent e) {
        //NOTHING
    }


    protected static String translateKeyEvent(KeyEvent e)
    {
        String keyString;

        int keyCode = e.getKeyCode();
        keyString = KeyEvent.getKeyText(keyCode);

        String locationS = "KBD::";
        int location = e.getKeyLocation();

        if (location == KeyEvent.KEY_LOCATION_LEFT) {
            locationS += "LEFT_";
        } else if (location == KeyEvent.KEY_LOCATION_RIGHT) {
            locationS += "RIGHT_";
        }

        return locationS+keyString;
    }

    protected static String translateKeyEvent(int i)
    {
        String keyString;

        keyString = KeyEvent.getKeyText(i);

        String locationS = "KBD::";
//        int location = 0;
//
//        if (location == KeyEvent.KEY_LOCATION_LEFT) {
//            locationS += "LEFT_";
//        } else if (location == KeyEvent.KEY_LOCATION_RIGHT) {
//            locationS += "RIGHT_";
//        }

        return locationS+keyString;
    }
}
